// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcgXVz5YoUF89cNVIIdhMpGxw7mhCrtrQ',
    appId: '1:663414398790:web:54c78260d831d5ae180f47',
    messagingSenderId: '663414398790',
    projectId: 'smartbez',
    authDomain: 'smartbez.firebaseapp.com',
    storageBucket: 'smartbez.firebasestorage.app',
    measurementId: 'G-77GF2P5E61',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-fzIkOxhofGGktXukUE7IpldHuvMxRXs',
    appId: '1:663414398790:android:f028f1a16ab6e1f5180f47',
    messagingSenderId: '663414398790',
    projectId: 'smartbez',
    storageBucket: 'smartbez.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALytjza7WbCeXCuE3Gpks-TcjNpZc03FY',
    appId: '1:663414398790:ios:eb1d276a68953c42180f47',
    messagingSenderId: '663414398790',
    projectId: 'smartbez',
    storageBucket: 'smartbez.firebasestorage.app',
    iosBundleId: 'com.example.smartbez',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALytjza7WbCeXCuE3Gpks-TcjNpZc03FY',
    appId: '1:663414398790:ios:eb1d276a68953c42180f47',
    messagingSenderId: '663414398790',
    projectId: 'smartbez',
    storageBucket: 'smartbez.firebasestorage.app',
    iosBundleId: 'com.example.smartbez',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcgXVz5YoUF89cNVIIdhMpGxw7mhCrtrQ',
    appId: '1:663414398790:web:0f60c2682578df9c180f47',
    messagingSenderId: '663414398790',
    projectId: 'smartbez',
    authDomain: 'smartbez.firebaseapp.com',
    storageBucket: 'smartbez.firebasestorage.app',
    measurementId: 'G-9F9SDL678H',
  );
}
